name: Github Publish

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'floss'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/
          
      - name: Display structure of downloaded files
        run: ls -R
      # 2
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Flarax_$(date +"%Y.%m.%d_%H-%M")"
      # 3
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/app/outputs/apk/release/app-release.apk
